# Generated by Django 2.1.2 on 2018-10-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dataset', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=300)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svm.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svm.Label'),
        ),
    ]
