# Generated by Django 2.1.2 on 2018-10-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svm', '0002_auto_20181008_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='dataset_id',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='label_id',
            new_name='label',
        ),
    ]
