# Generated by Django 2.1.2 on 2018-10-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svm', '0003_auto_20181008_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
