# Generated by Django 2.1.2 on 2018-11-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svm', '0005_remove_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
