# Generated by Django 2.1.2 on 2018-11-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svm', '0006_label_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='{{ MEDIA_URL }} upload-pictures'),
        ),
    ]
